config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  root "messages#index" 
  get 'from_user/:id' => "messages#from_user", as: :from_user
  get 'users/all' => "users#index", as: :all_users
  get 'followers/:id' => "timeline#followers", as: :followers
  get 'followed/:id' => "timeline#followed", as: :followed

  resources :messages
  post 'follow/:id' => 'following#create', as: :follow
  delete 'unfollow/:id' => 'following#destroy', as: :unfollow

end

app/models/following.rb
class Following
  include Mongoid::Document
  
  belongs_to :user, :class_name => "User", index: true
  belongs_to :followed_user, :class_name => "User", index: true
  
end

app/models/message.rb
class Message
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :content, type: String
  field :place_of_publishing, type: String

  belongs_to :user, index: true

  validates_length_of :content, minimum: 1, maximum: 140
  validates_length_of :place_of_publishing, maximum: 30
  
  scope :owned, -> (user_id) { where(user_id: user_id) }
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :login,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  field :verified, type: Boolean
  field :image, type: String
  field :username, type: String
  field :background_image, type: String
  field :description, type: String

  has_many :messages
  has_many :followed_users, class_name: "Following", inverse_of: :user

  validates_length_of :username, maximum: 16
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  protected

  def configure_permitted_parameters
    [:image, :background_image, :username, :description, :email].each do |param|
      devise_parameter_sanitizer.for(:account_update) << param
    end
  end
end

app/controllers/following_controller.rb
class FollowingController < ApplicationController

  def create
    Following.create(user_id: current_user.id, followed_user_id: params[:id])
    
    redirect_to from_user_path(params[:id])
  end

  def destroy
    following = Following.where(user_id: current_user.id, followed_user_id: params[:id])
    following.destroy

    redirect_to from_user_path(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  layout "timeline"

  def index
    @messages = Message.in(user_id: current_user.followed_users.map(&:followed_user_id)).sort(_id: -1).limit(50)
  end

  def from_user
    @messages = Message.where(user_id: params[:id]).sort(_id: -1).limit(50)
  end

  def show
    @message = Message.find(params[:id])
  end

  def create
    @message = Message.new(message_params.merge(user_id: current_user.id))

    if @message.save
      redirect_to from_user_path(current_user)
    else
      render :new
    end
  end

  def new
    @message = Message.new
  end

  def edit
    @message = Message.find(params[:id])
  end

  def update
    @message = Message.find(params[:id])
    @message.update_attributes(message_params)
    redirect_to from_user_path(current_user)  
  end

  def destroy
    @message = Message.find(params[:id]).destroy
    redirect_to from_user_path(current_user)
  end

  def message_params
      params.require(:message).permit(:content, :place_of_publishing)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController 
  layout :resolve_layout

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  private

  def resolve_layout
    case action_name
    when "new", "create"
      "application"
    else
      "timeline"
    end
  end
end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController

  def followers
    @user = User.find(params[:id])
    @users = User.in(:id => Following.where(:followed_user_id => @user).map(&:user_id))
  end

  def followed
    @user = User.find(params[:id])
    @users = User.in(:id => @user.followed_users.map(&:followed_user_id))
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "timeline"
  
  def index
    @users = User.not.in(id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?
 
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)
 
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML
 
    html.html_safe
  end
end

app/helpers/messages_helper.rb
module MessagesHelper

  def user_wrote_link(message)
    if message.user.username.present?
      text = "#{message.user.username} wrote:"
    else
      text = "#{message.user.email} wrote:"
    end

    link_to text, from_user_path(message.user)   
  end
end

app/helpers/timeline_helper.rb
module TimelineHelper

  def messages_link
    from_user_path(user_on_page.id) if user_on_page
  end

  def messages_count
    Message.where(user_id: user_on_page.id).count if user_on_page
  end

  def followers_link
    followers_path(user_on_page.id) if user_on_page
  end

  def followed_link
    followed_path(user_on_page.id) if user_on_page
  end    

  def user_on_page
    if params[:id].present? && user = User.where(_id: params[:id]).first
      @user_on_page ||= user
    else
      @user_on_page ||= current_user
    end
  end

  def followed_count
     Following.where(:user_id => user_on_page).count
  end

  def followers_count
    Following.where(:followed_user_id => user_on_page).count
  end

  def show_follow_unfollow_link?
    if current_user.id.to_s == params[:id] || params[:id].blank?
      false
    else
      true
    end
  end
  
  def follow_unfollow_link
    if Following.where(user_id: current_user.id, followed_user_id: params[:id])[0]
      link_to "Unfollow", unfollow_path(params[:id]), method: :delete
    else
      link_to "Follow", follow_path(params[:id]), method: :post
    end
  end

  def choose_class(path)
    if action_name.match path
      "active"
    else
      ""
    end
  end
end

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hirundo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body background="http://wallforu.com/wp-content/uploads/tree_nature_wallpaper.jpg">

    <div class="navbar navbar-fluid-top bg-success"></div>
    <%= render partial: "shared/flash_messages", flash: flash %> 
    <div class="container">
      <div class="row">
        <div class = "col-md-8">
          <%= yield :new_password %>
        </div>
        <div class = "col-md-4">
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="form-group">
                <%= form_for(:user, :url => session_path(:user), :method => :post, :html => { :class => "navbar-form navbar-left"}) do |f| %>
                  <p><%= f.text_field :email, :class => "form-control", :placeholder => "Email" %></p>
                  <%= f.password_field :password, :class => "form-control", :placeholder => "Password" %>
                  <p>
                  <%= f.check_box :remember_me %>
                  <%= f.label :remember_me %>
                  </p>
                  <%= f.submit 'Sign in', :class => "btn btn-primary" %>
                  <%= link_to "Forgot your password?", new_password_path(:user) %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class = "col-md-8"></div>
          <div class = "col-md-4">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="form-group">
                  <%= form_for(:user, url: registration_path(:user), :method => :post, :html => { :class => "navbar-form navbar-left"}) do |f| %>
                   <%= devise_error_messages! %>
                    <p><%= f.email_field :email, autofocus: true, :class => "form-control", :placeholder => "Email" %></p>
                    <p><%= f.password_field :password, autocomplete: "off", :class => "form-control", :placeholder => "Password" %></p>
                    <p><%= f.password_field :password_confirmation, autocomplete: "off", :class =>"form-control", :placeholder => "Password Confirmation" %></p>
                    <p>
                      <%= f.submit "Sign up", :class => "btn btn-warning" %>
                    </p>
                  <% end %>
               </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </body>
</html>

app/views/layouts/timeline.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hirundo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <% if user_on_page && user_on_page.background_image.present? %>
    <body background=<%= user_on_page.background_image%>>
  <% else %>
    <body class="background-image-clouds">
  <% end %>
    <div class="navbar navbar-fluid-top bg-success">
      <div class="navbar-inner">
        <div class="container-fluid">
          <ul class="nav nav-pills pull-left">
            <li role="presentation" class="active"><%= link_to "Home", root_path%></li>
            </ul>
          <ul class="nav nav-pills pull-right"> 
            <li role="presentation" class="navbar-form" role="search">
              <input type="text" class="form-control" placeholder="Search">
              <button type="submit" class="btn btn-default">Search</button>
            </li>
            <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                  More<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li role="presentation"><%= link_to "Profile", edit_user_registration_path %></li>
                  <li role="presentation"><%= link_to "Log out", destroy_user_session_path, method: :delete%></li>
                </ul>
              </li>
            <li role="presentation"><%= link_to "Write on your wall", new_message_path%></li>
          </ul> 
        </div>
      </div>
    </div>
    <br/>
    <br/>
    <br/>
    <div class="container">
    <div class="row">
        <div class = "col-sm-3"></div>
        <div class = "col-sm-6">
           <%= render partial: "shared/flash_messages", flash: flash %>
        </div>
        <div class = "col-sm-3"></div>
    </div>
    </div>
    <div class="container">
      <div class="row">
        <div class = "col-sm-3"></div>
        <div class = "col-sm-6">
          <nav class="navbar navbar-fluid">
            <ul class="nav nav-tabs pull-left">
              <li role="presentation" class=<%= choose_class('from_user') %>><a href="<%= messages_link %>">Messages <span class="badge"> <%= messages_count %></span></a></li>
              <li role="presentation" class=<%= choose_class('followed') %>><a href="<%= followed_link %>">Following <span class="badge"> <%= followed_count %> </span></a></li>
              <li role="presentation" class=<%= choose_class('followers') %>><a href="<%= followers_link %>">Followers <span class="badge"> <%= followers_count%></span></a></li>
            </ul>
            <% if show_follow_unfollow_link? %>
              <ul class="nav nav-pills pull-right">
                <li role="presentation" class="active"><%= follow_unfollow_link %></li>
              </ul>
            <% end %>
          </nav>
        </div>
        <div class = "col-sm-3"></div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <div class="thumbnail">
            <% if user_on_page.image.present? %>
              <%= link_to image_tag(user_on_page.image), from_user_path(user_on_page), :class => "thumbnail" %>
            <% end %>
            <div class="caption">
              <p><%= user_on_page.email %></p>
              <p><%= "Joined #{user_on_page.updated_at.strftime("%B")} #{user_on_page.updated_at.strftime("%Y")}" %></p>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="jumbotron backgound-white">
            <%= yield %>
          </div>
        </div>
        <div class="col-sm-3">
          <p class="navbar-text">
            Who to follow
            <br/>
            <%= link_to "View all", all_users_path%>
          </p>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="form-group">
      <%= form_for(@message, :html => { :class => "navbar-form navbar-left"}) do |f| %>
           <% if @message.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@message.errors.count, "error") %> prohibited this msg from being saved:</h2>
              <ul>
                <% @message.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <p><%= f.text_area :content, :class => "form-control", :placeholder => "Message" %></p>
        <p><%= f.text_field :place_of_publishing, :class => "form-control", :placeholder => "Place of publishing" %></p>
        <%= f.submit 'Create', :class => "btn btn-info" %>
      <% end %>
    </div>
  </div>
</div>

app/views/messages/edit.html.erb
<%= render partial: 'form' %>

app/views/messages/from_followed_users.html.erb
<%= render partial: 'shared/messages' %>

app/views/messages/from_user.html.erb
<%= render partial: 'shared/messages'%>

app/views/messages/index.html.erb
<div id="messages">
  <%= render partial: 'shared/messages'%>
</div>

app/views/messages/index.js.erb
jQuery("#messages").replaceWith('<%=j render 'shared/messages' %>');

app/views/messages/new.html.erb
<%= render partial: 'form' %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="list-group">
  <% @messages.each do |message| %>
      <h4 class="list-group-item-heading"><%=user_wrote_link(message)%></h4>
      <h3 class="list-group-item-text"><%= message.content %></h3>
      <p class="list-group-item-text"><%= message.place_of_publishing%></p>
      <p class="list-group-item-text"><%= "created at #{message.created_at.strftime("%e %b %Y %H:%M:%S%p")}"%></p>
      <% if current_user.id == message.user.id %>
        <%= link_to "Edit", edit_message_path(message)%> <%= link_to "Destroy", message_path(message), method: :delete%>
      <% end %>
      <hr>
  <% end %>
</div>

app/views/shared/_users.html.erb
<table class="table table-hover">
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.email, from_user_path(user.id) %></td>
      <% if user.image.present? %>
        <td><%= image_tag(user.image, :width =>"50px", :height => "50px") %></td>
      <% end %>
    </tr>
    <%end%>
</table>

app/views/timeline/followed.html.erb
<%= render partial: "shared/users" %>

app/views/timeline/followers.html.erb
<%= render partial: "shared/users" %>

app/views/users/index.html.erb
<%= render partial: "shared/users" %>